version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "QD-8148"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /next/
    commit-message:
      prefix: "QD-8148"
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
